const request = require('request');

module.exports.refresh = (req, res) => {
  const token = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDcyMzc4NjMsInVzZXJfbmFtZSI6IjkwNjQwMTAxIiwianRpIjoiOTI1ODNkNWItYzllMC00MjM0LWI5M2EtN2VmZjU0NmQzNDJmIiwiY2xpZW50X2lkIjoiMTBlOWM5NzZkNTc1NDA2M2ExMDNlNmM4OTM4ZWRkOWEiLCJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOnByb2ZpbGU6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOmJpbGxpbmc6cmVhZCIsImFsbGVncm86YXBpOmNhbXBhaWducyIsImFsbGVncm86YXBpOmRpc3B1dGVzIiwiYWxsZWdybzphcGk6YmlkcyIsImFsbGVncm86YXBpOnNhbGU6b2ZmZXJzOnJlYWQiLCJhbGxlZ3JvOmFwaTpvcmRlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTphZHMiLCJhbGxlZ3JvOmFwaTpwYXltZW50czp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6d3JpdGUiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOnJlYWQiLCJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczpyZWFkIiwiYWxsZWdybzphcGk6cGF5bWVudHM6cmVhZCJdLCJhbGxlZ3JvX2FwaSI6dHJ1ZX0.Rfvl5ePzDyNPVMbF6lQWE8eFxpifT8-T4HOxoBdR2E6eLLMxde0YfJJVUEWXZNETBOILiRmjj-Gh3nXNiReMdGEBvXcPoJ7AXw0Wncq2OeA3lMlk7GOt7xa0_F47LZd9V0dnXHbBqbzs9nD7hULWsUSiXgT7DpZhcJLzavRpTzYLmi_HP-eJKm0JUCFX81V4avdHGcMEd70-45Qq0cxXKAu0_FIRw2H2mYUF1xQ86U6BSIQijGYdFLa9DcfwCdEn6fSzwX3gzY01C5kZGCwiyepGU-IG_OhCTlr6o0kFtU16B5YdpW93qWuavtZJnm0KtC7dvn9Tz5WrMVG7yliPfQ';
  const refreshToken = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiI5MDY0MDEwMSIsInNjb3BlIjpbImFsbGVncm86YXBpOm9yZGVyczpyZWFkIiwiYWxsZWdybzphcGk6cHJvZmlsZTp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6b2ZmZXJzOndyaXRlIiwiYWxsZWdybzphcGk6YmlsbGluZzpyZWFkIiwiYWxsZWdybzphcGk6Y2FtcGFpZ25zIiwiYWxsZWdybzphcGk6ZGlzcHV0ZXMiLCJhbGxlZ3JvOmFwaTpiaWRzIiwiYWxsZWdybzphcGk6c2FsZTpvZmZlcnM6cmVhZCIsImFsbGVncm86YXBpOm9yZGVyczp3cml0ZSIsImFsbGVncm86YXBpOmFkcyIsImFsbGVncm86YXBpOnBheW1lbnRzOndyaXRlIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczp3cml0ZSIsImFsbGVncm86YXBpOnByb2ZpbGU6cmVhZCIsImFsbGVncm86YXBpOnJhdGluZ3MiLCJhbGxlZ3JvOmFwaTpzYWxlOnNldHRpbmdzOnJlYWQiLCJhbGxlZ3JvOmFwaTpwYXltZW50czpyZWFkIl0sImFsbGVncm9fYXBpIjp0cnVlLCJhdGkiOiI5MjU4M2Q1Yi1jOWUwLTQyMzQtYjkzYS03ZWZmNTQ2ZDM0MmYiLCJleHAiOjE2MTQ5NzA2NjMsImp0aSI6IjFhMjc2ZTU2LTUwZTUtNGVmNy04ZjY4LTJhOWEwOWI0MTg4ZCIsImNsaWVudF9pZCI6IjEwZTljOTc2ZDU3NTQwNjNhMTAzZTZjODkzOGVkZDlhIn0.M7txCC_5KLt8iyv4AWmtc7esMun0Rz8kl_JWM06Rzg0JUJ6EKSb6H5TuBLPD8LqEPaos65bouQOEzrKvV5ABbJJ4pe75nnx5TXnFsQN86dE1FAnacBsut4IfEGwyETvN9UTDRwgXvmTbepZpIIZxQuObrT0ryu4UUlfFliBTbHv13j9B3ddSD8qlrFs-brcYuBvSrxyllyQG_HpBIgVFcY7UMhPa0A4mrWt1mZEO2sHLcHJy4hDs-bTEZrPtGxYlYoMzFIrn7NvSYtYpxNouGXOqYcGVGn3tNsBTHdXfV_KhSNnLRbJG2qiWjbeMTGCjvJdSjhxsWbaGedLo8i8x9Q'

  const clientId = "10e9c976d5754063a103e6c8938edd9a";
  const secretKey = "ZqW6TjprKcxaJv3DibgjyPVSma2GkzFRX6H7bNTvTtE1TKrcoW22kJfZqBYKUTXp";
  const url = `https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=${refreshToken}`;
  const auth = "Basic " + new Buffer(clientId + ":" + secretKey).toString("base64");

request(
    {
        url : url,
        headers : {
            "Authorization" : auth
        }
    },
    function (error, response, body) {
        // console.log(error)
        // console.log(response)
        res.send(body)
    }
  )
}